<a href="https://colab.research.google.com/github/Aryan-jpg/Mini-Project/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from skimage.io import imread
from skimage.transform import resize 
import os 
import matplotlib.pyplot as plt

target=[]
images=[]
flatdata=[]

data='/content/drive/MyDrive/project'
categories=['apple','banana','pineapple']
for c in categories:
  value=categories.index(c)
  path=os.path.join(data,c)
  for img in os.listdir(path):
    images=imread(os.path.join(path,img))
    img_resize=resize(images,(120,120,3))
    flatdata.append(img_resize.flatten())
    target.append(value)

flatdata=np.array(flatdata)
target=np.array(target)





In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(flatdata,target,test_size=0.25,random_state=10)


In [3]:
len(x_test)

34

In [4]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid=[
             {'C': [1, 10, 100], 'gamma': [0.1,0.01,0.001],'kernel': ['rbf', 'poly', 'sigmoid']},
          ]

svc=svm.SVC(probability=True)
grid=GridSearchCV(svc,param_grid)
grid.fit(x_train,y_train)


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100], 'gamma': [0.1, 0.01, 0.001],
                          'kernel': ['rbf', 'poly', 'sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [5]:
y_pred=grid.predict(x_test)
y_pred


array([2, 1, 0, 1, 2, 1, 2, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2, 0, 0, 0, 0, 2,
       2, 2, 2, 2, 1, 1, 2, 0, 1, 0, 0, 2])

In [6]:
y_test

array([1, 1, 0, 1, 2, 1, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 2,
       2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 0, 2])

In [7]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_pred,y_test)


array([[10,  0,  2],
       [ 0,  7,  0],
       [ 1,  5,  9]])

In [8]:
svcacc1=accuracy_score(y_pred,y_test)
svcacc1

0.7647058823529411

In [9]:
#algo 1
from sklearn.svm import SVC
model1=SVC()
model1.fit(x_train,y_train)
y_pred=model1.predict(x_test)
y_pred

array([2, 1, 0, 1, 2, 1, 2, 2, 2, 2, 0, 0, 1, 0, 2, 2, 2, 0, 2, 0, 0, 2,
       0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 2])

In [10]:
y_test

array([1, 1, 0, 1, 2, 1, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 2,
       2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 0, 2])

In [11]:
svcacc=accuracy_score(y_pred,y_test)
svcacc

0.7647058823529411

In [12]:
#algo2
from xgboost import XGBClassifier
model2=XGBClassifier()
model2.fit(x_train,y_train)
y_pred=model2.predict(x_test)
y_pred


array([1, 1, 0, 1, 2, 1, 2, 2, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 0, 0, 0, 2,
       2, 1, 2, 1, 1, 1, 2, 0, 1, 0, 0, 2])

In [13]:
confusion_matrix(y_pred,y_test)

array([[10,  1,  1],
       [ 0, 11,  2],
       [ 1,  0,  8]])

In [14]:
xgacc=accuracy_score(y_pred,y_test)
xgacc

0.8529411764705882

In [15]:
#algo3
from sklearn.ensemble import RandomForestClassifier
randomf=RandomForestClassifier(n_estimators=50,random_state=0)
randomf.fit(x_train, y_train)
y_pred = randomf.predict(x_test)
y_pred

array([1, 1, 0, 1, 2, 1, 0, 2, 2, 2, 0, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 2,
       2, 2, 2, 2, 1, 1, 2, 0, 1, 0, 0, 2])

In [16]:
confusion_matrix(y_pred,y_test)

array([[10,  0,  1],
       [ 0,  9,  0],
       [ 1,  3, 10]])

In [17]:
randomfacc=accuracy_score(y_pred,y_test)
randomfacc

0.8529411764705882

In [18]:
#algo4
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 10)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred


array([1, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 1, 0, 0, 0, 0, 1,
       0, 1, 2, 1, 1, 1, 2, 2, 1, 0, 0, 2])

In [19]:
y_test

array([1, 1, 0, 1, 2, 1, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 2,
       2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 0, 2])

In [20]:
confusion_matrix(y_pred,y_test)

array([[ 9,  2,  5],
       [ 0, 10,  1],
       [ 2,  0,  5]])

In [21]:
knnacc=accuracy_score(y_pred,y_test)
knnacc

0.7058823529411765

In [22]:
#algo5
from sklearn.naive_bayes import MultinomialNB
mul = MultinomialNB()
mul.fit(x_train, y_train)
y_pred=mul.predict(x_test)
y_pred

array([1, 1, 0, 2, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 2, 2, 1, 0, 2, 0, 0, 1,
       0, 1, 2, 1, 1, 1, 2, 2, 1, 1, 0, 2])

In [23]:
y_test

array([1, 1, 0, 1, 2, 1, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 0, 0, 0, 0, 2,
       2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 0, 2])

In [24]:
confusion_matrix(y_pred,y_test)

array([[7, 1, 2],
       [1, 9, 5],
       [3, 2, 4]])

In [25]:
mulacc=accuracy_score(y_pred,y_test)
mulacc

0.5882352941176471

In [26]:
#pickle 
import pickle
pickle.dump(model2,open('img.p','wb'))


In [27]:
#logic=pickle.load(open('img.p','rb'))


In [28]:
#flat_data=[]
#url=input('enter img url')
#img=imread(url)
#img_re=resize(img,(120,120,3))
#flat_data.append(img_re.flatten())
#flat_data=np.array(flat_data)
#plt.imshow(img_re)
#out=logic.predict(flat_data)
#output=categories[out[0]]
#print(f'the img is={output}')

In [29]:
!pip install streamlit --quiet
!pip install pyngrok==4.1.1 --quiet
from pyngrok import ngrok


In [35]:
%%writefile app.py
import streamlit as st
from PIL import Image
import numpy as np
from skimage.io import imread
from skimage.transform import resize
import pickle
categories=['apple','banana','pineapple'] 
flatdata=[]
st.title('Image Classifier')
st.header('Upload a image')
logic=pickle.load(open('img.p','rb'))
uploaded_file=st.file_uploader('UPLOAD HERE',type='jpg') 
if uploaded_file is not None:
  img=Image.open(uploaded_file)
  st.image(img,caption='Uploaded image')
  if st.button('Predict'):
    st.title('Result....')
    img=np.array(img)
    img_resized=resize(img,(120,120,3))
    flatdata.append(img_resized.flatten())
    flatdata=np.array(flatdata)
    y_out=logic.predict(flatdata)
    y_out=categories[y_out[0]]
    st.write(f'The Predicted output fot the given image is = "{y_out}"')


Overwriting app.py


In [31]:
!nohup streamlit run app.py &
url = ngrok.connect(port='8501')
print(url)


nohup: appending output to 'nohup.out'
http://6c03fa6e07e0.ngrok.io
